{
 "title": "Tesla Tracker",
 "description": "Track a Tesla",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "vehicle",
    "label": "Vehicle",
    "query": "SELECT state->>'id' FROM vehicles"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Range",
   "type": "singlestat",
   "description": "The current range of the vehicle.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  battery_range\nFROM battery\nWHERE\n  $__timeFilter(\"time\") AND\n  vehicle = $vehicle\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Shift State",
   "type": "singlestat",
   "description": "The current shift state of the vehicle.",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  shift_state\nFROM location\nWHERE\n  $__timeFilter(\"time\")\n  AND shift_state IS NOT NULL\n  AND vehicle = $vehicle\nORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Current State",
   "type": "singlestat",
   "description": "The state of the vehicle.",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT initcap(status) FROM uptime WHERE time < $__timeTo() AND time > $__timeFrom() AND vehicle = $vehicle ORDER BY time DESC LIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Charge State",
   "type": "singlestat",
   "description": "The charge state of the vehicle.",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  charging_state\nFROM battery\nWHERE\n  $__timeFilter(\"time\")\n  AND charging_state IS NOT NULL\n  AND vehicle = $vehicle\nORDER BY time DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Charge Rate",
   "type": "singlestat",
   "description": "The current charge rate of the vehicle.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  charge_rate\nFROM battery\nWHERE\n  $__timeFilter(\"time\") AND\n  vehicle = $vehicle\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "graph",
   "description": "The battery level of the vehicle.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  battery_level\nFROM battery\nWHERE\n  $__timeFilter(\"time\") AND\n  vehicle = $vehicle\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Battery Range",
   "type": "graph",
   "description": "The battery range of the vehicle.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  battery_range\nFROM battery\nWHERE\n  $__timeFilter(\"time\") AND\n  vehicle = $vehicle\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Charge Rate",
   "type": "graph",
   "description": "The charge rate of the vehicle.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  charge_rate\nFROM battery\nWHERE\n  $__timeFilter(\"time\") AND\n  vehicle = $vehicle\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Odometer Miles",
   "type": "graph",
   "description": "The amount of miles on the vehicle.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "lengthmi" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"time\" AS \"time\",\n  (state->'vehicle_state'->>'odometer')::float\nFROM telemetry\nWHERE\n  $__timeFilter(\"time\") AND\n  vehicle = $vehicle\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Idle Time",
   "type": "singlestat",
   "description": "The idle time of the vehicle.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT CONCAT(EXTRACT(HOUR FROM ($__timeTo() - time)), ' hours and ', EXTRACT(MINUTE FROM ($__timeTo() - time)), ' minutes') as idle_time FROM location WHERE time < $__timeTo() AND shift_state IS NOT NULL AND shift_state != 'P' AND vehicle = $vehicle ORDER BY time DESC LIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Odometer",
   "type": "singlestat",
   "description": "The odometer reading of the vehicle.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 21 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT (state->'vehicle_state'->>'odometer')::float as odometer FROM telemetry WHERE time > $__timeFrom() AND time < $__timeTo() AND vehicle = $vehicle ORDER BY time DESC LIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Idle Loss",
   "type": "singlestat",
   "description": "The idle loss of the vehicle.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "WITH last_idle_time AS (\r\n    SELECT time FROM location WHERE time < $__timeTo() AND shift_state IS NOT NULL AND shift_state != 'P' AND vehicle = $vehicle ORDER BY time DESC LIMIT 1\r\n), range AS (\r\n  SELECT battery_range FROM battery WHERE battery.time IN (SELECT time FROM last_idle_time) AND vehicle = $vehicle\r\n) SELECT ((SELECT battery_range FROM range) - (state->'charge_state'->>'battery_range')::float) FROM vehicles WHERE vehicle = $vehicle"
    }
   ]
  },
  {
   "title": "Last Telemetry Event",
   "type": "singlestat",
   "description": "The last telemetry event from the vehicle.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT CONCAT(to_char(EXTRACT(EPOCH FROM ($__timeTo() - time) / 60), '9999999999D'), ' minutes ago') as last_contact FROM telemetry WHERE time < $__timeTo() AND vehicle = $vehicle ORDER BY time DESC LIMIT 1\r\n"
    }
   ]
  }
 ]
}